[package]
name = "vocksel/mock"
description = "Package for creating Jest-like mocks for use with unit testing."
version = "0.1.1"
authors = [ "David Minnerly <me@vocksel.com>" ]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "*.spec.lua"
]

[dependencies]
TestEZ = "roblox/testez@0.4.1"